### ISSUE TITLE
Please share on FreeCAD User Showcase sub-forum

### ISSUE THREAD

**Issue by luzpaz** [OSRLab/vertical_grow_tower#1]
It would be nice if you posted your work on https://forum.freecadweb.org/viewforum.php?f=24 and showcase it to the FC community. Have you heard of [Open Source Ecology](http://opensourceecology.org/wiki/G-Towers), btw ?

**Comment by odellus** [comment]
I hadn't heard of them what I remember but I did build and use the PVC towers from YouTube. This repo is pretty much 100% bc Larry wants to get rich on his fucking tower design and it's too simple not to make an open source version. It's so simple I could masquerade this as a FreeCAD tutorial on scripting with Python. I posted it on the FreeCAD forum @ https://forum.freecadweb.org/viewforum.php?f=22 but will post on user showcase as soon as I'm able to (can't post twice too quickly). 

Thank you so much for your interest. 🤗✊🤘
